# Main Stuff
title: Partners
url: partners.streamdata.io

# Partners
philosophy: This is the Streamdata.io partner center. Where we showcase and engage with other technology providers in the space. We have worked to establish a relationship with each of the companies below, from helping them evolve their services, to being a reseller, and publishing our solutions in their marketplace. Take a look at our current partners, then maybe consider if your product or service might be a fit for working with Streamdata.io and our customers.

partners:
  - name: Xignite
    ranking: 1
    description: Xignite inspire the future of finance by making market data easy.
    url: http://www.xignite.com/
    image: https://i1.wp.com/streamdata.io/wp-content/uploads/2018/01/xignite-1.png?fit=150%2C39&ssl=1
    latest:
      - title: Xignite, A Leader In Market Data Streaming API
        url: https://streamdata.io/blog/xignite-market-data-streaming-api-leader/
      - title: Postman Collections For Each Xignite Global Currencies API
        url: https://streamdata.io/blog/postman-collections-xignite-currencies-api/
  - name: Amazon web Services
    ranking: 2
    description: Amazon Web Services offers reliable and scalable cloud computing services.
    url: https://aws.amazon.com/
    image: https://i0.wp.com/streamdata.io/wp-content/uploads/2018/01/amazon.png?fit=147%2C56&ssl=1
    latest:
      - title: An AWS Lambda Function For Streaming New Hacker News Posts Into Your S3 Data Lake
        url: https://streamdata.io/blog/aws-lambda-function-streaming-new-hacker-news-posts-into-s3-data-lake/
      - title: An AWS Lambda Function For Streaming Twitter Searches Into Your S3 Data Lake
        url: https://streamdata.io/blog/aws-lambda-function-for-streaming-twitter-searches-into-your-s3-data-lake/
  - name: Talend
    ranking: 3
    description: Talend is the world leader in big data cloud integration solutions.
    url: https://www.talend.com
    image: https://i0.wp.com/streamdata.io/wp-content/uploads/2018/04/Talend-logo.png?fit=150%2C59&ssl=1
    latest:
        - title: The Next Generation Of Extract Transform and Load At TalendConnect
          url: https://streamdata.io/blog/next-generation-extract-transform-load-talendconnect/
        - title: When ESB and API worlds merge, @talend data streams with our historic partner Restlet to interconnect with API launched in TalendConnect
          url: https://twitter.com/StreamdataIO/status/993858516094996481
  - name: Trading Central
    ranking: 4
    description: Trading Central is the leader in the field of financial markets analysis.
    url: https://www.tradingcentral.com/
    image: https://i1.wp.com/streamdata.io/wp-content/uploads/2018/01/trading_central.png?fit=104%2C68&ssl=1
  - name: 3Scale
    ranking: 5
    description: 3Scale helps to build a more programmable web through its API management platform.
    url: https://www.3scale.net/
    image: https://i1.wp.com/streamdata.io/wp-content/uploads/2018/01/3scale-1.png?fit=148%2C46&ssl=1
    latest:
        - title: 3Scale Technology Partner
          url: https://www.3scale.net/partners/streamdata-io/
        - title: Streaming APIs and the Internet of Things
          url: https://www.3scale.net/2015/09/streaming-apis-and-the-internet-of-things/
  - name: ChartIQ
    ranking: 6
    description: ChartIQ creates HTML5 financial charting and data visualization solutions for capital markets.
    url: https://www.chartiq.com/
    image: https://i0.wp.com/streamdata.io/wp-content/uploads/2018/01/chartiq.png?fit=138%2C42&ssl=1
    latest:
        - title: How to take ChartIQ one step further with real-time data?
          url: https://streamdata.io/blog/how-to-take-chartiq-one-step-further-with-real-time-data/
        - title: ChartIQ Angular demo
          url: https://github.com/streamdataio/streamdataio-ChartIQ-Angular-demo
  - name: Google Cloud Platform
    ranking: 7
    description: Google Cloud Platform lets developers build, deploy, and scale applications, websites, and services on the same infrastructure as Google.
    url: https://cloud.google.com/
    image: https://i2.wp.com/streamdata.io/wp-content/uploads/2018/01/Google_Cloud.png?fit=114%2C65&ssl=1
    latest:
        - title: Streaming Data into Google BigQuery Using Streamdata.io
          url: https://streamdata.io/blog/streaming-data-google-bigquery/
        - title: Streamdata.io earns Google Technological Partner Status
          url: https://streamdata.io/blog/google-technological-partner/
  - name: Pivotal
    ranking: 8
    description: Pivotal enables the leading companies in the world to innovate by employing an approach focused on building software.
    url: https://pivotal.io/
    image: https://i2.wp.com/streamdata.io/wp-content/uploads/2018/01/pivotal.png?fit=136%2C33&ssl=1
    latest:
        - title: Setting up a streaming API with Pivotal Web Services and Streamdata.io
          url: https://streamdata.io/blog/streaming-api-pivotal-streamdataio/s
        - title: Streamdata.io vs. Pivotal Web Services (PWS)
          url: https://stackshare.io/stackups/pivotal-web-services-vs-streamdata-io
  - name: Kong
    ranking: 9
    description: Kong and Streamdata.io partner to deliver best-in-class API management solution to developers.
    url: https://konghq.com/
    image: https://i2.wp.com/streamdata.io/wp-content/uploads/2018/02/kong-blue2.png?fit=300%2C99&ssl=1
    latest:
        - title: Streaming Kong API Endpoint Activity With Server-Sent Events (SSE)
          url: https://streamdata.io/blog/streaming-kong-api-endpoint-activity-server-sent-events-sse/
        - title: Breaking Down Kong API Gateway Plugins
          url: https://streamdata.io/blog/breaking-down-kong-api-gateway-plugins/
  - name: IBM
    ranking: 10
    description: The IBM Marketplace is a digital store where you can discover, try, and buy software, hardware, and services from both IBM and third-party vendors and Streamdata.io is the first streaming API service available in the marketplace.
    url: https://www.ibm.com/products
    image: https://i1.wp.com/streamdata.io/wp-content/uploads/2018/05/ibmpos_grey.jpg?fit=170%2C62&ssl=1
    latest:
        - title: Streamdata.io in the IBM Marketplace
          url: https://www.ibm.com/us-en/marketplace/8099
        - title: Connect Streamdata.io to IBM Bluemix Issued Device Allocation
          url: https://apiant.com/connect/Streamdata.io-to-IBM-Bluemix-Issued-Device-Allocation
  - name: QuantHouse
    ranking: 11
    description: QuantHouse is the global independent provider of high performance API-based market data and algo trading services.
    url: https://www.quanthouse.com/
    image: https://i0.wp.com/streamdata.io/wp-content/uploads/2018/05/quanthouse.jpg?fit=170%2C42&ssl=1
  - name: Nasdaq
    ranking: 12
    description: Your data is time-sensitive -- access real-time market data via an API provider with advanced server pushing and consumption analytics at a lower cost.
    url: https://www.nasdaq.com/
    image: https://i0.wp.com/streamdata.io/wp-content/uploads/2018/05/nasdaq-logo.png?fit=170%2C64&ssl=1
  - name: Salesforce
    ranking: 13
    description: Salesforce is the primary enterprise offering within the Salesforce platform. It provides companies with an interface for case management and task management, and a system for automatically routing and escalating important events.
    url: https://www.salesforce.com/uk/?ir=1
    image: https://i2.wp.com/streamdata.io/wp-content/uploads/2018/05/Salesforce-partner.png?fit=170%2C170&ssl=1
    latest:
        - title: Exploring SalesForce PushTopic Queries
          url: https://streamdata.io/blog/salesforce-pushtopic-queries-api/
        - title: Breaking Down The Salesforce Streaming API
          url: https://streamdata.io/blog/salesforce-streaming-api/
  - name: APIMetrics
    ranking: 14
    description: APIMetrics created the industry’s best real-time API & Cloud Service monitoring and analytics. In fact, they’re the industry’s first and only intelligent, analytics-driven API performance solution built specifically for enterprise.
    url: https://apimetrics.io/
    image: https://i2.wp.com/streamdata.io/wp-content/uploads/2018/05/APImetrics.png?fit=170%2C43&ssl=1
    latest:
        - title: Cutting The HTTP Status Code Noise Out Of API Monitoring Streams
          url: https://streamdata.io/blog/cutting-http-status-code-noise/
        - title: APIMetrics in the Streamdata.io API Gallery
          url: http://apimetrics.api.gallery.streamdata.io/
  - name: Postman
    ranking: 15
    description: The Postman toolchain can help to build software that is useful across various use cases ranging from a single developer to an enterprise. We are building for the future where everything is going to be connected.
    url: https://www.getpostman.com/
    image: https://i0.wp.com/streamdata.io/wp-content/uploads/2018/05/Postman-logo.png?fit=170%2C68&ssl=1
    latest:
        - title: Postman For Server-Sent Event (SSE) APIs
          url: https://streamdata.io/blog/postman-for-server-sent-event-sse-apis/
        - title: Converting Postman Collections Into OpenAPI Definitions
          url: https://streamdata.io/blog/postman-collections-openapi-definitions/
  - name: Axway
    ranking: 16
    description: Realizing the transformational power in every customer.
    url: http://axway.com
    image: https://i1.wp.com/streamdata.io/wp-content/uploads/2018/05/Axway-logo.png?fit=170%2C60&ssl=1
    latest:
        - title: Streamdata.io Is Available In The Axway Marketplace
          url: https://streamdata.io/blog/streamdata-io-is-available-in-the-axway-marketplace/
        - title: Streamdata.io In The Axway Marketplace
          url: https://marketplace.axway.com/apps/147407#!overview
  - name: TIBCO Cloud Mashery
    ranking: 17
    description: TIBCO is a global leader in integration, API management, and analytics. With the TIBCO Connected Intelligence Cloud, TIBCO executes on digital transformation strategies with thousands of customers with its innovative technology.
    url: https://www.mashery.com/
    image: https://i2.wp.com/streamdata.io/wp-content/uploads/2018/07/TCMash-1.png?fit=822%2C246&ssl=1

# Other Settings
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

github_user: streamdata-projects
github_repo: partners
github_branch: master
